# Maybe:
# one between
# - distance (must have a Sun) - scalar
# - origin - vector

# moons as sub--array-of-tables

# in config a way to configure the "tail" (on|off, color, length...)

[config]
# TODO: mass_unit = "Yg"
# TODO: distance_unit = "Gm"
# TODO: orbital_velocity_unit = "km/s"

# TODO: visual_radius = 448.8
    motion_trail_length = 1550  # default length for motion trail (in px) | default: 0 (disabled)
    default_px_radius = 5.     # default radius for objects (in px)      | default: 5.
    default_color = 0x994C00   # default color for objects (hex or int)  | default: 0x994C00

[[object]]
    name = "Mario"
    mass =  5974.2
    distance = 200.6
    orbital_velocity = 29.8

[[object]]
    name = "sun"
    mass = 1988435000
    distance = 0
    orbital_velocity = 0

    px_radius = 10
    color = 0xFFFF00
    motion_trail_length = 0

[[object]]
    name = "mercury"
    mass = 330.11
    distance = 46.00
    orbital_velocity = 58.98


    px_radius = 2.
    color = 0x79757D

[[object]]
    name = "venus"
    mass = 4867.5
    distance = 107.48
    orbital_velocity = 35.26
    color = 0xC1792E

[[object]]
    name = "earth"
    mass =  5972.3
    distance = 147.9
    orbital_velocity = 30.29

    color = 0x0080FF

    [[object.satellites]]
        name = "moon"
        mass = 73.46
        distance = [0., 0.3633, 0.]
        orbital_velocity = [0., 0., 1.082]

        px_radius = 1
        color = 0x79757D

[[object]]
    name = "mars"
    mass =  641.71
    distance = 206.62
    orbital_velocity = 26.5

    color = 0xD17252

[[object]]
    name = "jupiter"
    mass =  1898190
    distance = 740.52
    orbital_velocity = 13.72

    color = 0xFF9933

[[object]]
    name = "saturn"
    mass =  568340
    distance = 1352.55
    orbital_velocity = 10.18

    color = 0xFFFF99

[[object]]
    name = "uranus"
    mass =  86813
    distance = 2741.3
    orbital_velocity = 7.11

    color = 0xCCFFFF

[[object]]
    name = "neptune"
    mass =  102413
    distance = 4444.45
    orbital_velocity = 5.5

    color = 0x3333FF

[[object]]
    name = "pluto"
    mass =  13.03
    distance = 4436.82
    orbital_velocity = 6.1

    color = 0xA19E91

[[object]]
    name = "eris"
    mass = 16.6
    distance = 14062.199
    orbital_velocity = 3.4338

    color = 0x93A6BD

